chore: update dependency @sap/artifact-management to v1.20.1
SAP/app-studio-toolkit pull request #213
Opened 2023-03-19 09:49 UTC by ThreeWind

There is a request of getting ProjectApi object by a specific path from cicd (https://jira.tools.sap/browse/LCAP-2883). Project API add a new api to support such request and release the patch 1.20.1 for it. So I submit the pull request to make cicd can use the new api via app-studio-toolkit.

As to refactor Project API to add  a new VSCode wrapper as npm module, there still are some concerns and require more time to clarify them on Project API side.

2023-03-20 09:49 UTC, EstherPerelman requested changes
Looks good, I'm not familiar with the new "getProject" function and its args - I believe you tested/compared it against the implementation

2023-03-20 09:49 UTC, EstherPerelman commented on packages/app-studio-toolkit/test/public-api/create-workspace-proxy.spec.ts
>      it("exposes only three properties", () => {
minor...
```suggestion
    it("exposes only four properties", () => {
```

2023-03-20 15:32 UTC, EstherPerelman approved these changes

2023-03-20 15:45 UTC, merged

2023-03-21 01:27 UTC, ThreeWind commented
> Looks good, I'm not familiar with the new "getProject" function and its args - I believe you tested/compared it against the implementation

Thanks for your review. Yes, we have sufficient unit tests for the implementation to assure it is correct on Project API side.

2023-03-21 23:57 UTC, thomaszang commented
@ThreeWind / @ThreeWind, after this PR was merged, it is already available in BAS's staging landscape, right? when can it be available in Canary landscape?