feat: support action in package.json
SAP/app-studio-toolkit pull request #22
Opened 2021-03-05 13:13 UTC by idoprz

one of the tests didn't passed. After discussion with Ira, I think it was local problem. Let's check it before merging this PR

2021-03-05 13:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SAP/app-studio-toolkit?pullRequest=22) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SAP/app-studio-toolkit?pullRequest=22) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAP/app-studio-toolkit?pullRequest=22) it.</sub>

2021-03-07 13:07 UTC, tomer-epstein requested changes

2021-03-07 13:07 UTC, tomer-epstein commented on tests/basctlServer.spec.ts
> +    it.only("startBasctlServer socket exists, " +
remove .only

2021-03-07 13:07 UTC, tomer-epstein commented on tests/extension.spec.ts
> +import * as basctlServer from '../src/basctlServer/basctlServer';
![image](https://user-images.githubusercontent.com/57438361/110240921-c9884c80-7f56-11eb-8f43-2a4b66ed3d56.png)

2021-03-07 15:21 UTC, idoprz commented on tests/basctlServer.spec.ts
> +    it.only("startBasctlServer socket exists, " +
fixed

2021-03-08 07:49 UTC, tomer-epstein requested changes

2021-03-08 07:49 UTC, tomer-epstein commented on src/actions/controller.ts
> +    getContributorExtension() {
getContributorExtensions or getContributorsActions

2021-03-08 07:49 UTC, tomer-epstein commented on src/actions/controller.ts
> +
remove

2021-03-08 08:17 UTC, merged