Adding id parameter to Action object
SAP/app-studio-toolkit pull request #28
Opened 2021-03-11 10:51 UTC by NetaMolcho

2021-03-11 15:51 UTC, idoprz reviewed
see my comments in line. otherwise it's fine by me, but Tomer should approve. not me.

2021-03-11 15:51 UTC, idoprz commented on package.json
> +		"@sap/consume-services-types": "^0.3.6",
The toolkit should not be dependant on the consume services. It is lower level extension.
You should either define the IService in the toolkit, or use some more "abstract type" (preferable not any)

2021-03-11 15:51 UTC, idoprz commented on src/actions/interfaces.ts
> +import { IService } from "@sap/consume-services-types";
remove this dependency...

2021-03-11 15:51 UTC, idoprz commented on src/actions/interfaces.ts
> +export type SnippetActionParams = any | {data: any, service: IService} | {data: any};
it can be service: any
or better to define something in here that will cover the service type

2021-03-11 19:16 UTC, idoprz submitted a review, later dismissed
👍

2021-03-14 09:05 UTC, tomer-epstein requested changes
increment version 0.0.4--> https://github.com/NetaMolcho/app-studio-toolkit/blob/idAction/package.json#L5
increment version 0.0.4 (too) --> https://github.com/NetaMolcho/app-studio-toolkit/blob/idAction/types/package.json#L4

2021-03-14 09:09 UTC, tomer-epstein approved these changes

2021-03-14 09:20 UTC, merged